import Head from 'next/head'
import Navbar from "./Navbar"
import Footer from "./Footer"

export default function Layout({ children }) {
    return (
      <>
        <Head>
          <title>Fake Site</title>
          <meta name="firststreet fakesite" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navbar />
          <main>{children}</main>
        <Footer />

      </>
    )
  }