import Head from 'next/head'
import Image from 'next/image'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Fake Site</title>
        <meta name="firststreet fakesite" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="hero-image">
          <div className="hero-container">
            <h1>The world's greatest fake site</h1>
            <p>Create the world's greatest fake site and enjoy
            <br/>
            the breeze of fresh air when you complete it</p>
            <button className="hero-button">Do something awesome</button>
          </div>
        </div>
      </main>

      <footer>
        <h1>Footer</h1>
      </footer>

      <style jsx>
        {`

        `}
      </style>
    </div>
  )
}
